AWSTemplateFormatVersion: '2010-09-09'
Description: InterCountNet – EC2 + Docker + S3-read role (Ubuntu 22.04)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  GithubRepo:
    Type: String
  S3Bucket:
    Type: String
  InstanceType:
    Type: String
    Default: t3.medium

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH + Streamlit port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # lock to your IP later
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  S3ReadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref S3ReadRole]

  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default: [install_and_run]   # single config-set, full control

        install_and_run:
          commands:
            01_enable_univ:
              command: "sudo add-apt-repository -y universe"
            02_update:
              command: "sudo apt-get update"
            03_docker:
              command: "sudo apt-get install -y docker.io git awscli python3-distutils"
            04_docker_group:
              command: "sudo usermod -aG docker ubuntu"
            05_clone:
              command: !Sub |
                sudo -u ubuntu bash -c 'git clone ${GithubRepo} /home/ubuntu/repo'
            06_build:
              command: "sudo -u ubuntu bash -c 'cd /home/ubuntu/repo && docker build -t intercountnet .'"
            07_run:
              command: !Sub |
                sudo -u ubuntu bash -c 'docker run -d --restart unless-stopped \
                -p 80:8501 \
                -e MODEL_BUCKET=${S3Bucket} \
                --name app intercountnet'
    Properties:
      ImageId: ami-0c7217cdde317cfec          # Ubuntu 22.04 LTS us-east-1
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref SecurityGroup]
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt-get update -y
          apt-get install -y python3-pip

          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz

          ln -s /usr/local/bin/cfn-init /usr/bin/cfn-init || true
          ln -s /usr/local/bin/cfn-signal /usr/bin/cfn-signal || true

          /usr/local/bin/cfn-init -v \
            --stack ${AWS::StackName} \
            --resource EC2Instance \
            --configsets default \
            --region ${AWS::Region}
          /usr/local/bin/cfn-signal -e $? \
            --stack ${AWS::StackName} \
            --resource EC2Instance \
            --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: intercountnet-ec2
    CreationPolicy:
      ResourceSignal:
        Timeout: PT20M

Outputs:
  PublicIp:
    Description: Public IP of the instance
    Value: !GetAtt EC2Instance.PublicIp
  StreamlitURL:
    Description: Streamlit browser URL
    Value: !Sub 'http://${EC2Instance.PublicIp}'
